all:
	g++ -O3 Client.cpp -o client
	g++ -O3 Server.cpp -o server 
	g++ -O3 PingClient.cpp -o pingClient
	g++ -O3 BandWidthClient.cpp -o bandWidthClient
	g++ -O3 BandWidthServer.cpp -o bandWidthServer
	g++ -O3 SetupTime.cpp       -o setupTime
clean:
	rm -rf *o server
	rm -rf *o client
	rm -rf *o pingClient
	rm -rf *o bandWidthClient
	rm -rf *o bandWidthServer
